# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_memory <- function(i) {
    .Call(`_binsegRcpp_read_memory`, i)
}

read_new <- function(i) {
    .Call(`_binsegRcpp_read_new`, i)
}

read_malloc <- function(i) {
    .Call(`_binsegRcpp_read_malloc`, i)
}

rcpp_binseg_normal <- function(data_vec, max_segments) {
    .Call(`_binsegRcpp_rcpp_binseg_normal`, data_vec, max_segments)
}

rcpp_binseg_normal_cost <- function(data_vec, max_segments) {
    .Call(`_binsegRcpp_rcpp_binseg_normal_cost`, data_vec, max_segments)
}

